version: "3.1"
services:
    php-fpm:
        build: docker/php-fpm
        container_name: shop-php
        working_dir: /app
        volumes:
            - ./:/app
    nginx:
        image: nginx:alpine
        container_name: shop-nginx
        working_dir: /app
        volumes:
            - ./:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/log/nginx:/var/log/nginx
        ports:
            - "80:80"
            - "8080:8080"
            - "443:443"
